---
# This playbook deploys the whole application stack for a sonar.

- hosts: sonar-server
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

- name: Install Java 11
  hosts: sonar-server
  roles:
    - role: ansible-role-java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-11-jdk

- name: Install sonarqube
  hosts: sonar-server
  roles:
    - ansible-role-sonarqube

- name: Applies HAProxy config for SSL
  hosts: localhost
  become: true
  roles:
    - role: ansible-role-haproxy
